### ISSUE TITLE
Load to editor causes assertion error

### ISSUE THREAD

**Issue by jonpas** [intercept/intercept#101]
When loading with startup parameter to load directly into an editor mission (eg. `arma3.exe "c:\arma3\users\myUser\missions\myMission.intro\mission.sqm"`) causes the following assertion error:
http://i.imgur.com/u4JGItP.png

**Comment by dedmen** [comment]
This is because lib.sqf not executing at preInit. I also have that problem without going directly to editor.
Some eventhandler is being triggered. Which calls to intercept which wasn't initialized yet and... crash.
Should just add a check on incoming eventhandlers to just drop the message if not initialized yet

**Comment by dedmen** [comment]
So yeah.. Its caused because lib.sqf is not executed at preInit.. I'd say we should switch to using XEH for the preInit event... We have dependency on CBA_XEH anyway in CfgPatches. I don't know why.. Didn't see XEH used anywhere. But should be used. I'll test that fix later and make a PR

**Comment by jonpas** [comment]
I believe XEH is required for actually hooking into the events or something like it.

**Comment by dedmen** [comment]
Oops.. Yeah.. The Macro in config.cpp resolves to XEH handlers.

**Comment by dedmen** [comment]
Btw This would also trigger when going to Editor and Placing a Unit. That would trigger an EH and crash.
#112 is not a real fix for the underlying problem. We have no checks to make sure the Invoker is initialized before trying to Invoke something.
