### ISSUE TITLE
Generic Script Error on sqf::call

### ISSUE THREAD

**Issue by RZSenfo** [intercept/intercept#146]
Due to the fact that assignments don't return nil, but NOTHING: 
The sqf::call wrapper assigns the result of a call to a variable which can be NOTHING because of said fact.
This can cause a generic script error.

**Comment by dedmen** [comment]
This can be solved by not always grabbing a return value.
This can either be done by implementing two additional sqf::call wrappers that just return nothing. Or using a dynamic approach that detects whether the user even want's a return value.
SQF function to call script without return value
```sqf
intercept_fnc_callWrapper_NoReturn = {
	scopeName "main";
	(missionNamespace getVariable "INTERCEPT_CALL_ARGS") params ["_args", "_code"];
	_args call _code;
	INTERCEPT_DUMMY;
};
```

A wrapper that detects whether the return value is needed could look like this:
```c++
/**
         * @brief Wrapper for return value of sqf::call
         * @desc This will call the script function and only fetch the return value if you use/store it. 
         */
        class call_ret_val {
        public:
            explicit call_ret_val(game_value args_) : args(args_) {}
            call_ret_val(const call_ret_val&) = delete;
            call_ret_val(call_ret_val&&) = delete;
            call_ret_val& operator=(const call_ret_val&) = delete;
            call_ret_val& operator=(call_ret_val&&) = delete;
            operator game_value&& () const { return get_return_value(); }
            game_value&& operator*() const { return get_return_value(); };
            game_value&& operator->() const { return get_return_value(); };
            ~call_ret_val() {
                if (executed) return;
                set_variable(mission_namespace(), "INTERCEPT_CALL_ARGS", args);
                host::functions.invoke_raw_unary(
                    __sqf::unary__isnil__code_string__ret__bool,
                    get_variable(mission_namespace(), "intercept_fnc_callWrapper_NoReturn")
                );
            }
        private:
            game_value&& get_return_value() const {
                //Cannot be done more than once
                assert(!executed);
                set_variable(mission_namespace(), "INTERCEPT_CALL_ARGS", args);
                host::functions.invoke_raw_unary(
                    __sqf::unary__isnil__code_string__ret__bool,
                    get_variable(mission_namespace(), "intercept_fnc_callWrapper")
                );
                executed = true;
                return std::move(get_variable(mission_namespace(), "INTERCEPT_CALL_RETURN"));
            }
            const game_value args;
            bool executed{ false };
        };
```

Which works fine in almost all cases.
```c++
game_value ret = sqf::call(code); //Calls conversion operator which returns result of get_return_value()
sqf::call(code); //Return value is never used. Which means it destructs right after this call meaning we call the function without grabbing a return value
(*sqf::call(code)).size(); //uses operator* which returns result of get_return_value();
std::string ret = sqf::call(code); //implicitly calls operator game_value&& and game_value's conversion operator to std::string
object ret = sqf::call(code); //implicitly calls operator game_value&& and conversion to object.
```
I don't really like that you would have to use (*). to get the return value.
We cannot use operator-> because that returns a pointer. And we only have a temporary here. We could however return the result of the call inside `call_ret_val` and return the pointer to that. But that could go bad if you use the to_array function of game_value to get a auto_array reference. `call_ret_val` and thus the game_value might get destroyed before you are done working with the auto_array ref.
The bigger problem is following
```c++
auto ret = sqf::call(code); //Doesn't compile. Because auto deduces to call_ret_val which can't be assigned using operator=
auto ret = *sqf::call(code); //Fine. Calls operator* which returns rvalue game_value and move assigns it into ret which deduced to game_value
```
This would break a lot of code.

The absolute best solution would be using operator. which returns the stored return value.
(http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0252r0.pdf)
But it doesn't look like it will make it into c++17

**Comment by dedmen** [comment]
@NouberNou What do you think? This would all be fine if we disallow the use of `auto` for variables that store the returned data from sqf::call. Many people will stumble over that probably. We can probably add that as a `remark` in the Documentation of sqf::call which should make it quite clear to the user. If the user doesn't want to read the documentation then it's his fault when he does stuff wrong.

If the user uses "anything" other than auto. It will compile and behave as expected.
Anything here being anything that game_value can convert to.

**Comment by commy2** [comment]
Why not this?
```sqf
intercept_fnc_callWrapper = {
	scopeName "main";
	(missionNamespace getVariable "INTERCEPT_CALL_ARGS") params ["_args", "_code"];
	[_x] apply {_args call _code} select 0
};
```
Btw, `_args` and `_code` will be changed in the called code.

**Comment by RZSenfo** [comment]
Good catch if that really works

**Comment by commy2** [comment]
Should maybe prefix the locals with `_intercept_` to avoid collisions.

This method already takes care of `_x`, but in scheduled that might be undefined and result in an error.
```sqf
[if (!isNil "_x") then {_x}]
```
as work-around if that's a concern.

**Comment by dedmen** [comment]
We can't be scheduled. So that's not a concern.
